name: compradordodia
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.2.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+2
  flutter_slidable_list_view: ^1.2.8
  http: ^0.12.0+1
  flutter_masked_text: ^0.8.0
  flutter_money_formatter: ^0.8.3
  date_format: ^1.0.8
  firebase_messaging: ^6.0.16
  validadores: ^1.0.2
  google_maps_flutter: ^0.5.19+2
  geolocator: ^5.3.2+2
  flutter_multi_formatter: ^1.1.6
  table_calendar: ^2.2.3
  flutter_time_picker_spinner: ^1.0.6+1
  firebase_analytics: ^5.0.16
  flutter_phone_state: ^0.5.9
  flutter_mobx: ^1.1.0+2
  mobx: ^1.2.1+4
  mobx_codegen: ^1.1.2
  shared_preferences: ^0.5.12+4
  chips_choice: ^2.0.1
  url_launcher: ^5.7.10
  whatsapp_unilink: ^1.0.0+1
  flutter_webview_plugin: ^0.3.11
  google_sign_in: ^4.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5
  build_runner: ^1.7.3



flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/icon/Icon_100x100px.png"
  adaptive_icon_foreground: "dev_assets/icon/Icon_100x100px.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/gerarevento.png
    - images/grupo.png
    - images/listacompras.png
    - images/icone_arquivo.png
    - images/icone_camera.png
    - images/incluir_foto_laranja.png
    - images/cheque_verde.jpg
    - images/icone_casa.jpg
    - images/semfoto.png
    - images/whatsapp.jpg
    - images/g-1.jpg
    - images/f-1.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
